all:
	g++ main.cpp Field.cpp SDL_main.m Timer.cpp Ball.cpp -I../bin/ -I/Library/Frameworks/SDL.framework/Headers -framework SDL -framework Cocoa -framework AppKit -framework Foundation -L../bin/ -lvec2d -arch i386
